name: Databricks Development Workflow

on:
  pull_request:
    branches: [develop]

jobs:
  databricks-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install databricks CLI as per https://docs.databricks.com/dev-tools/cli/databricks-cli.html
    - name: Install databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    # List the databricks repos within the workspace whose credentials
    # are stored in the Github Environment "my-environment"
    - name: List databricks repos
      env:
        # Note the host is an "environment variable" in the Github Environment
        # while the token is a "secret" in the Github Environment
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
      run: |
        databricks repos list

    - name: Upload script to DBFS
      run: |
        databricks fs cp codes/script.py dbfs:/scripts/script.py