name: Databricks Development Workflow

on:
  pull_request:
    branches: [develop]
env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
  #DATABRICKS_DEV_CLUSTER_ID: ${{ secrets.DATABRICKS_DEV_CLUSTER_ID }}
jobs:
  databricks-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Create directory in DBFS
      run: |
        databricks fs mkdirs dbfs:/scripts

    - name: Upload script to DBFS
      run: |
        databricks fs cp codes/script.py dbfs:/scripts/script.py
    - name: Create Job
      run: |
        databricks jobs create --json '{
          "name": "Local Job",
          "existing_cluster_id": "${{ secrets.DATABRICKS_DEV_CLUSTER_ID }}",
          "notebook_task": {
            "notebook_path": "/scripts/script.py"
          }
        }'
